lettings/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.index, name='lettings_index'),
    path('<int:letting_id>/', views.letting, name='letting'),
]

oc_lettings_site/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views


def zero_division_error(request):
    return 1 / 0


urlpatterns = [
    path('', views.index, name='index'),
    path('lettings/', include(('lettings.urls', 'lettings'), namespace='lettings')),
    path('profiles/', include(('profiles.urls', 'profiles'), namespace='profiles')),
    path('admin/', admin.site.urls),
    path('sentry-debug/', zero_division_error),
]

profiles/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.index, name='profiles_index'),
    path('<str:username>/', views.profile, name='profile'),
]

lettings/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinLengthValidator


class Address(models.Model):
    number = models.PositiveIntegerField(validators=[MaxValueValidator(9999)])
    street = models.CharField(max_length=64)
    city = models.CharField(max_length=64)
    state = models.CharField(max_length=2, validators=[MinLengthValidator(2)])
    zip_code = models.PositiveIntegerField(validators=[MaxValueValidator(99999)])
    country_iso_code = models.CharField(max_length=3, validators=[MinLengthValidator(3)])

    def __str__(self):
        return f'{self.number} {self.street}'

    class Meta:
        verbose_name_plural = "Addresses"


class Letting(models.Model):
    title = models.CharField(max_length=256)
    address = models.OneToOneField(Address, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

profiles/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    favorite_city = models.CharField(max_length=64, blank=True)

    def __str__(self):
        return self.user.username

lettings/views.py
from django.shortcuts import render
from .models import Letting


# Aenean leo magna, vestibulum et tincidunt fermentum, consectetur quis velit.
# Sed non placerat massa. Integer est nunc, pulvinar a tempor et, bibendum id arcu.
# Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;
# Cras eget scelerisque
def index(request):
    lettings_list = Letting.objects.all()
    context = {'lettings_list': lettings_list}
    return render(request, 'lettings/index.html', context)


# Cras ultricies dignissim purus, vitae hendrerit ex varius non.
# In accumsan porta nisl id eleifend.
# Praesent dignissim, odio eu consequat pretium, purus urna vulputate arcu,
# vitae efficitur lacus justo nec purus.
# Aenean finibus faucibus lectus at porta.
# Maecenas auctor, est ut luctus congue, dui enim mattis enim,
# ac condimentum velit libero in magna.
# Suspendisse potenti. In tempus a nisi sed laoreet.
# Suspendisse porta dui eget sem accumsan interdum.
# Ut quis urna pellentesque justo mattis ullamcorper ac non tellus.
# In tristique mauris eu velit fermentum, tempus pharetra est luctus.
# Vivamus consequat aliquam libero, eget bibendum lorem. Sed non dolor risus.
# Mauris condimentum auctor elementum. Donec quis nisi ligula.
# Integer vehicula tincidunt enim, ac lacinia augue pulvinar sit amet.
def letting(request, letting_id):
    letting = Letting.objects.get(id=letting_id)
    context = {
        'title': letting.title,
        'address': letting.address,
    }
    return render(request, 'lettings/letting.html', context)

oc_lettings_site/views.py
from django.shortcuts import render


# Lorem ipsum dolor sit amet, consectetur adipiscing elit.
# Quisque molestie quam lobortis leo consectetur ullamcorper non id est.
# Praesent dictum, nulla eget feugiat sagittis, sem mi convallis eros,
# vitae dapibus nisi lorem dapibus sem.
# Maecenas pharetra purus ipsum, eget consequat ipsum lobortis quis.
# Phasellus eleifend ex auctor venenatis tempus.
# Aliquam vitae erat ac orci placerat luctus.
# Nullam elementum urna nisi, pellentesque iaculis enim cursus in.
# Praesent volutpat porttitor magna, non finibus neque cursus id.
def index(request):
    return render(request, 'index.html')

profiles/views.py
from django.shortcuts import render
from .models import Profile


# Sed placerat quam in pulvinar commodo.
# Nullam laoreet consectetur ex, sed consequat libero pulvinar eget. Fusc
# faucibus, urna quis auctor pharetra, massa dolor cursus neque, quis dictum lacus d
def index(request):
    profiles_list = Profile.objects.all()
    context = {'profiles_list': profiles_list}
    return render(request, 'profiles/index.html', context)


# Aliquam sed metus eget nisi tincidunt ornare accumsan eget lac
# laoreet neque quis, pellentesque dui. Nullam facilisis pharetra vulputate.
# Sed tincidunt, dolor id facilisis fringilla, eros leo tristique lacus,
# it. Nam aliquam dignissim congue.
# Pellentesque habitant morbi tristique senectus et netus et males
def profile(request, username):
    profile = Profile.objects.get(user__username=username)
    context = {'profile': profile}
    return render(request, 'profiles/profile.html', context)

lettings/templates/lettings/index.html
<title>Lettings</title>
<h1>Lettings</h1>
{% if lettings_list %}
    <ul>
    {% for letting in lettings_list %}
        <li>
            <a href="{% url 'lettings:letting' letting_id=letting.id %}">
                {{ letting.title }}
            </a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No lettings are available.</p>
{% endif %}
<div><a href="{% url 'index' %}">Home</a></div>
<div><a href="{% url 'profiles:profiles_index' %}">Profiles</a></div>

lettings/templates/lettings/letting.html
<title>{{ title }}</title>
<h1>{{ title }}</h1>
<p>{{ address.number }} {{ address.street }}</p>
<p>{{ address.city }}, {{ address.state }} {{ address.zip_code }}</p>
<p>{{ address.country_iso_code }}</p>
<div><a href="{% url 'lettings:lettings_index' %}">Back</a></div>
<div><a href="{% url 'index' %}">Home</a></div>
<div><a href="{% url 'profiles:profiles_index' %}">Profiles</a></div>

lettings/templates/lettings_index.html
<title>Lettings</title>
<h1>Lettings</h1>
{% if lettings_list %}
    <ul>
    {% for letting in lettings_list %}
        <li>
            <a href="{% url 'lettings:letting' letting_id=letting.id %}">
                {{ letting.title }}
            </a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No lettings are available.</p>
{% endif %}
<div><a href="{% url 'index' %}">Home</a></div>
<div><a href="{% url 'profiles:profiles_index' %}">Profiles</a></div>

oc_lettings_site/templates/index.html
<title>Holiday Homes</title>
<h1>Welcome to Holiday Homes</h1>
<div><a href="{% url 'profiles:profiles_index' %}">Profiles</a></div>
<div><a href="{% url 'lettings:lettings_index' %}">Lettings</a></div>

profiles/templates/profiles/index.html
<title>Profiles</title>
<h1>Profiles</h1>
{% if profiles_list %}
    <ul>
    {% for profile in profiles_list %}
        <li>
            <a href="{% url 'profiles:profile' username=profile.user.username %}">
                {{ profile.user.username }}
            </a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No profiles are available.</p>
{% endif %}
<div><a href="{% url 'index' %}">Home</a></div>
<div><a href="{% url 'lettings:lettings_index' %}">Lettings</a></div>

profiles/templates/profiles/profile.html
<title>{{ profile.user.username }}</title>
<h1>{{ profile.user.username }}</h1>
<p>First name: {{ profile.user.first_name }}</p>
<p>Last name: {{ profile.user.last_name }}</p>
<p>Email: {{ profile.user.email }}</p>
<p>Favorite city: {{ profile.favorite_city }}</p>
<div><a href="{% url 'profiles:profiles_index' %}">Back</a></div>
<div><a href="{% url 'index' %}">Home</a></div>
<div><a href="{% url 'lettings:lettings_index' %}">Lettings</a></div>

profiles/templates/profiles_index.html
<title>Profiles</title>
<h1>Profiles</h1>
{% if profiles_list %}
    <ul>
    {% for profile in profiles_list %}
        <li>
            <a href="{% url 'profiles:profile' username=profile.user.username %}">
                {{ profile.user.username }}
            </a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No profiles are available.</p>
{% endif %}
<div><a href="{% url 'index' %}">Home</a></div>
<div><a href="{% url 'lettings:lettings_index' %}">Lettings</a></div>